/**
 * Role Templates
 *
 * Predefined permission sets for common roles.
 * Used by the RoleTemplateSelector to quickly configure
 * a custom role with sensible defaults.
 */

import type { Permission } from '@/lib/permissions';

export interface RoleTemplate {
  key: string;
  name: string;
  description: string;
  permissions: Permission[];
}

export const ROLE_TEMPLATES: RoleTemplate[] = [
  {
    key: 'DISPATCHER',
    name: 'Dispatcher',
    description: 'Load management, dispatch operations, and basic fleet visibility',
    permissions: [
      'loads.view',
      'loads.create',
      'loads.edit',
      'loads.assign',
      'drivers.view',
      'trucks.view',
      'trailers.view',
      'customers.view',
      'documents.view',
      'documents.upload',
      'calendar.view',
      'calendar.edit',
      'loadboard.view',
      'loadboard.post',
      'breakdowns.view',
      'fleet.monitoring',
      'settings.view',
    ],
  },
  {
    key: 'ACCOUNTANT',
    name: 'Accountant',
    description: 'Financial management, invoicing, settlements, and reporting',
    permissions: [
      'invoices.view',
      'invoices.create',
      'invoices.edit',
      'invoices.generate',
      'settlements.view',
      'settlements.create',
      'settlements.edit',
      'settlements.approve',
      'loads.view',
      'customers.view',
      'expenses.view',
      'expenses.approve',
      'analytics.view',
      'reports.view',
      'reports.export',
      'documents.view',
      'documents.upload',
      'batches.view',
      'batches.create',
      'batches.edit',
      'batches.post',
      'deduction_rules.view',
      'deduction_rules.create',
      'deduction_rules.edit',
      'advances.view',
      'advances.create',
      'advances.approve',
      'ifta.view',
      'ifta.calculate',
      'company_expenses.view',
      'company_expenses.create',
      'company_expenses.edit',
      'company_expenses.approve',
      'company_expenses.export',
      'payment_instruments.view',
      'payment_instruments.create',
      'company_expense_types.view',
      'company_expense_types.create',
      'department_budgets.view',
      'department_budgets.manage',
      'settings.view',
      'departments.accounting.view',
      'departments.reports.view',
    ],
  },
  {
    key: 'FLEET_MANAGER',
    name: 'Fleet Manager',
    description: 'Vehicle and trailer management, maintenance, and fleet operations',
    permissions: [
      'trucks.view',
      'trucks.create',
      'trucks.edit',
      'trailers.view',
      'trailers.create',
      'trailers.edit',
      'maintenance.view',
      'maintenance.create',
      'maintenance.edit',
      'breakdowns.view',
      'breakdowns.create',
      'breakdowns.edit',
      'inspections.view',
      'inspections.create',
      'inspections.edit',
      'fuel.view',
      'fuel.create',
      'fuel.edit',
      'vendors.view',
      'vendors.create',
      'vendors.edit',
      'drivers.view',
      'loads.view',
      'documents.view',
      'documents.upload',
      'fleet.reports',
      'fleet.costs',
      'fleet.communications',
      'fleet.hotspots',
      'fleet.on_call',
      'fleet.monitoring',
      'fleet.monitoring.settings',
      'ifta.view',
      'analytics.view',
      'reports.view',
      'reports.export',
      'settings.view',
      'departments.fleet.view',
      'departments.reports.view',
    ],
  },
  {
    key: 'SAFETY_OFFICER',
    name: 'Safety Officer',
    description: 'Safety compliance, inspections, incidents, and driver compliance management',
    permissions: [
      'safety.view',
      'safety.manage',
      'compliance.view',
      'compliance.manage',
      'drivers.view',
      'drivers.edit',
      'drivers.manage_compliance',
      'trucks.view',
      'trucks.edit',
      'trailers.view',
      'trailers.edit',
      'inspections.view',
      'inspections.create',
      'inspections.edit',
      'loads.view',
      'documents.view',
      'documents.upload',
      'safety.incidents.view',
      'safety.incidents.create',
      'safety.incidents.edit',
      'safety.drug_tests.view',
      'safety.drug_tests.create',
      'safety.drug_tests.edit',
      'safety.mvr.view',
      'safety.mvr.create',
      'safety.medical_cards.view',
      'safety.medical_cards.create',
      'safety.hos.view',
      'safety.hos.manage',
      'safety.dvir.view',
      'safety.dvir.create',
      'safety.dvir.edit',
      'safety.training.view',
      'safety.training.manage',
      'safety.compliance.view',
      'safety.compliance.manage',
      'safety.alerts.view',
      'safety.alerts.manage',
      'safety.tasks.view',
      'safety.tasks.create',
      'safety.tasks.edit',
      'safety.overview.view',
      'safety.reports.view',
      'safety.cdl.view',
      'analytics.view',
      'reports.view',
      'reports.export',
      'settings.view',
      'departments.safety.view',
      'departments.reports.view',
    ],
  },
  {
    key: 'HR_MANAGER',
    name: 'HR Manager',
    description: 'Driver and employee management, recruiting, and onboarding',
    permissions: [
      'drivers.view',
      'drivers.create',
      'drivers.edit',
      'users.view',
      'users.create',
      'users.edit',
      'loads.view',
      'documents.view',
      'documents.upload',
      'settings.view',
      'settings.edit',
      'company.view',
      'analytics.view',
      'reports.view',
      'reports.export',
      'crm.leads.view',
      'crm.leads.create',
      'crm.leads.edit',
      'crm.leads.assign',
      'crm.hire',
      'crm.onboarding.view',
      'crm.onboarding.manage',
      'departments.hr.view',
      'departments.reports.view',
      'departments.crm.view',
    ],
  },
];

/**
 * Get a role template by its key.
 */
export function getRoleTemplate(key: string): RoleTemplate | undefined {
  return ROLE_TEMPLATES.find((t) => t.key === key);
}

/**
 * Get all available role template keys.
 */
export function getRoleTemplateKeys(): string[] {
  return ROLE_TEMPLATES.map((t) => t.key);
}
