#!/bin/bash
# Helper script to guide user in getting Neon direct connection string

echo "🔍 Neon Direct Connection Setup Guide"
echo ""
echo "Since the guessed connection strings didn't work, you need to get the"
echo "EXACT connection string from Neon Dashboard."
echo ""
echo "📋 Steps to get your Direct Connection String:"
echo ""
echo "1. Go to: https://console.neon.tech"
echo "2. Select your project"
echo "3. Click on 'Connection Details' (or 'Settings' → 'Connection Details')"
echo "4. Look for connection type selector (usually tabs or dropdown)"
echo "5. Select 'Direct connection' (NOT 'Pooled connection')"
echo "6. Copy the ENTIRE connection string shown"
echo ""
echo "The connection string should look like one of these formats:"
echo ""
echo "  Format 1:"
echo "  postgresql://user:password@host.region.aws.neon.tech/database?sslmode=require"
echo ""
echo "  Format 2:"
echo "  postgresql://user:password@host.region.aws.neon.tech:5432/database?sslmode=require"
echo ""
echo "  Format 3:"
echo "  postgresql://user:password@host.region.aws.neon.tech/database?sslmode=require&other=params"
echo ""
echo "⚠️  Important:"
echo "   - The hostname should NOT contain '-pooler'"
echo "   - Copy the ENTIRE string including all parameters"
echo "   - It might include additional parameters like 'channel_binding'"
echo ""
echo "📝 Once you have the connection string, run:"
echo ""
echo "   nano .env"
echo ""
echo "   Add or update this line:"
echo "   DATABASE_URL_MIGRATE=\"paste-your-connection-string-here\""
echo ""
echo "   Save and exit (Ctrl+X, Y, Enter)"
echo ""
echo "   Then test with:"
echo "   npm run db:test-connection"
echo ""
echo "   And run migration:"
echo "   npm run db:migrate:deploy"
echo ""





